"""add language

Revision ID: 34046b7af1fc
Revises: 93cfaf09f651
Create Date: 2018-07-01 14:56:31.342359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34046b7af1fc'
down_revision = '93cfaf09f651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
